/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as QuemSomosRouteImport } from './routes/quem-somos'
import { Route as ProjetosRouteImport } from './routes/projetos'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as ComoAjudarRouteImport } from './routes/como-ajudar'
import { Route as IndexRouteImport } from './routes/index'

const QuemSomosRoute = QuemSomosRouteImport.update({
  id: '/quem-somos',
  path: '/quem-somos',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosRoute = ProjetosRouteImport.update({
  id: '/projetos',
  path: '/projetos',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const ComoAjudarRoute = ComoAjudarRouteImport.update({
  id: '/como-ajudar',
  path: '/como-ajudar',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/como-ajudar': typeof ComoAjudarRoute
  '/contato': typeof ContatoRoute
  '/projetos': typeof ProjetosRoute
  '/quem-somos': typeof QuemSomosRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/como-ajudar' | '/contato' | '/projetos' | '/quem-somos'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/como-ajudar' | '/contato' | '/projetos' | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/como-ajudar'
    | '/contato'
    | '/projetos'
    | '/quem-somos'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ComoAjudarRoute: typeof ComoAjudarRoute
  ContatoRoute: typeof ContatoRoute
  ProjetosRoute: typeof ProjetosRoute
  QuemSomosRoute: typeof QuemSomosRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/quem-somos': {
      id: '/quem-somos'
      path: '/quem-somos'
      fullPath: '/quem-somos'
      preLoaderRoute: typeof QuemSomosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos': {
      id: '/projetos'
      path: '/projetos'
      fullPath: '/projetos'
      preLoaderRoute: typeof ProjetosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/como-ajudar': {
      id: '/como-ajudar'
      path: '/como-ajudar'
      fullPath: '/como-ajudar'
      preLoaderRoute: typeof ComoAjudarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ComoAjudarRoute: ComoAjudarRoute,
  ContatoRoute: ContatoRoute,
  ProjetosRoute: ProjetosRoute,
  QuemSomosRoute: QuemSomosRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
